### ISSUE TITLE
Request help: specific tagged value 

### ISSUE THREAD

**Issue by pierremestrez1976** [emcodem/createaaf#1]
Hello,
Im not yet very familiar with python but well c/c++
Im looking to add some specific tagged value attached to mastermob. Metadata such as custom column, comment, locators and growing file tags.
Could you help where to do this in the code ?
Thanks
Pierre

**Comment by emcodem** [comment]
Hi Pierre,
to be honest, what you want requires less python skills than aaf knowledge and especially knowledge about what the pyaaf2 module can or cannot do. In the end, what you want to do maybe might just be 2 or 3 lines of code, so no need to understand python in general.
Even if you don't know python, you should be able to see that my code does not do much in regards to "creating" or "writing" the aaf.. instead it is more focussed about the "reading" part (parsing the materialpackage UMID). 
But i am with you, pyaaf2 is the only really useable API for small scale projects , using the base aafsdk would also add many days/weeks/months of R&D to what you want to do. 
However, i see 2 options for you, either you get more attention by posting your question in the ffastrans forum (in case you use ffastrans) or you get a little involved in python and the pyaaf2 libs and then ask here: https://github.com/markreidvfx/pyaaf2/issues 

Some helping tools on your way might be included here (e.g. thread page10): http://www.ffastrans.com/frm/forum/viewtopic.php?f=5&t=892&hilit=aaf+processing
